### ISSUE TITLE
Audio/Questions

### ISSUE THREAD

**Issue by Dontmindmes** [skillkit/go-ghome#1]
Is it possible to play an audio file? Also is deployment the same? 

Also what do I set the action name as on console

And will the application keep running even after task executed? So like every 30 minutes you could have it say something

**Comment by frozzare** [comment]
1. I haven't tried audio, but I don't think this package supports that.
2. You can't set action name in this package, maybe you need to do that on https://dialogflow.com/
3. No. Google send a request to the application and you response with an answer.

**Comment by Dontmindmes** [comment]
There are not clear tutorials for using dialog flow with GO, 

Do you have a more advanced example for using this? Like using it with voice commands or something

**Comment by Dontmindmes** [comment]
And how is deployment? Through dialog flow? Or through run main.go

**Comment by frozzare** [comment]
No I don't have any more advanced example than what exists in this repo. It's still a **work in progress** repo and no stable version of this package exists yet.

The deployment it's just like deploy a go app since you're Dialogflow action is sending a payload to your http endpoint. This is not uniq to Go and there documentation over at Dialogflow about this.
